let participantes = [
  //Categorias: alianza, pana, criminal, interesante
  {nombre: "Abbalon",           categoria: ""},
  {nombre: "Alexander",         categoria: ""},
  {nombre: "Altare",            categoria: "pana"},
  {nombre: "Aragaki",           categoria: "pana"},
  {nombre: "Aran",              categoria: "pana"},
  {nombre: "Asher S. Ravus",    categoria: "alianza"},
  {nombre: "Atenea",            categoria: "pana"},
  {nombre: "Ayame Seukha",      categoria: "pana"},
  {nombre: "Azai",              categoria: "pana"},
  {nombre: "Basilio Da Silva",  categoria: ""},
  {nombre: "Candras",           categoria: "pana"},
  {nombre: "Caronte",           categoria: "pana"},
  {nombre: "Clyne",             categoria: "pana"},
  {nombre: "Conrad",            categoria: ""},
  {nombre: "Cordelia Ravus",    categoria: "pana"},
  {nombre: "Dale",              categoria: "pana"},
  {nombre: "Dan",               categoria: ""},
  {nombre: "Delos",             categoria: ""},
  {nombre: "Diana",             categoria: ""},
  {nombre: "Dimitri Zimmer",    categoria: ""},
  {nombre: "Din",               categoria: ""},
  {nombre: "Doldo",             categoria: ""},
  {nombre: "Dorthe",            categoria: "pana"},
  {nombre: "Drakken",           categoria: "pana"},
  {nombre: "Dudu",              categoria: ""},
  {nombre: "Eli",               categoria: "pana"},
  {nombre: "Elliot",            categoria: "pana"},
  {nombre: "Érika Gein",        categoria: ""},
  {nombre: "Farin Barbabronce", categoria: "alianza"},
  {nombre: "Fir Raiga",         categoria: "pana"},
  {nombre: "Garp",              categoria: ""},
  {nombre: "Gerras",            categoria: ""},
  {nombre: "Gray",              categoria: "pana"},
  {nombre: "Groh",              categoria: "pana"},
  {nombre: "Hevth Gridewal",    categoria: "pana"},
  {nombre: "Iemon",             categoria: ""},
  {nombre: "Ilya",              categoria: "pana"},
  {nombre: "Ina Krabong",       categoria: ""},
  {nombre: "Jesse",             categoria: ""},
  {nombre: "Johannes Nagi",     categoria: ""},
  {nombre: "Kaela Zesiger",     categoria: "pana"},
  {nombre: "Karma",             categoria: ""},
  {nombre: "Keaton",            categoria: ""},
  {nombre: "Kobo",              categoria: "pana"},
  {nombre: "Konan Aveis",       categoria: ""},
  {nombre: "Lee",               categoria: ""},
  {nombre: "Leonardo",          categoria: "pana"},
  {nombre: "Levin",             categoria: ""},
  {nombre: "Lionel",            categoria: ""},
  {nombre: "Lirio",             categoria: ""},
  {nombre: "Lurko",             categoria: "pana"},
  {nombre: "Maiki",             categoria: ""},
  {nombre: "Makoto",            categoria: "pana"},
  {nombre: "Millicent Melnyk",  categoria: "pana"},
  {nombre: "Miyama Yoino",      categoria: ""},
  {nombre: "Mokichi Robinson",  categoria: ""},
  {nombre: "Nadia Naqjati",     categoria: "pana"},
  {nombre: "Nagito",            categoria: "asesino"},
  {nombre: "Naoto Dubois",      categoria: ""},
  {nombre: "Nobunaga",          categoria: ""},
  {nombre: "Norio",             categoria: "pana"},
  {nombre: "Orion",             categoria: "alianza"},
  {nombre: "Palermo",           categoria: ""},
  {nombre: "Qi",                categoria: "asesino"},
  {nombre: "Rafael",            categoria: ""},
  {nombre: "Randolph Wagnis",   categoria: "pana"},
  {nombre: "Reinhold Eunibu",   categoria: ""},
  {nombre: "Riju",              categoria: ""},
  {nombre: "Roc",               categoria: "alianza"},
  {nombre: "Roy",               categoria: ""},
  {nombre: "Sanzu",             categoria: "pana"},
  {nombre: "Seigen",            categoria: ""},
  {nombre: "Shin Rosewald",     categoria: "alianza"},
  {nombre: "Shorath",           categoria: "pana"},
  {nombre: "Siddartha",         categoria: ""},
  {nombre: "Silque",            categoria: ""},
  {nombre: "Sinbad",            categoria: ""},
  {nombre: "Soleil Eunibu",     categoria: "pana"},
  {nombre: "Tai Lung",          categoria: "asesino"},
  {nombre: "Thorphin",          categoria: ""},
  {nombre: "Tia",               categoria: ""},
  {nombre: "Tokuno Tokumichi",  categoria: ""},
  {nombre: "Tomoe Itoo",        categoria: "pana"},
  {nombre: "Tyra Lang",         categoria: ""},
  {nombre: "Uno Yoino",         categoria: ""},
  {nombre: "Vashalla",          categoria: "pana"},
  {nombre: "Ventra",            categoria: ""},
  {nombre: "Voldia Dupont",     categoria: ""},
  {nombre: "Wilhelm",           categoria: "pana"},
  {nombre: "Xaldir Fertira",    categoria: "alianza"},
  {nombre: "Xianghua",          categoria: ""},
  {nombre: "Xiatago",           categoria: ""},
  {nombre: "Zalan",             categoria: "alianza"},
  {nombre: "Zen'Reel",          categoria: "zen"},
  {nombre: "Zeta",              categoria: "pana"},
  {nombre: "Zohel",             categoria: "alianza"},
];